# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/gateway.proto for package 'gateway_protocol'

require 'grpc'
require 'zeebe/client/proto/gateway_pb'

module Zeebe::Client::GatewayProtocol
  module Gateway
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gateway_protocol.Gateway'

      rpc :Topology, TopologyRequest, TopologyResponse
      rpc :DeployWorkflow, DeployWorkflowRequest, DeployWorkflowResponse
      rpc :PublishMessage, PublishMessageRequest, PublishMessageResponse
      rpc :UpdateJobRetries, UpdateJobRetriesRequest, UpdateJobRetriesResponse
      rpc :FailJob, FailJobRequest, FailJobResponse
      rpc :CompleteJob, CompleteJobRequest, CompleteJobResponse
      rpc :CreateWorkflowInstance, CreateWorkflowInstanceRequest, CreateWorkflowInstanceResponse
      rpc :CancelWorkflowInstance, CancelWorkflowInstanceRequest, CancelWorkflowInstanceResponse
      rpc :UpdateWorkflowInstancePayload, UpdateWorkflowInstancePayloadRequest, UpdateWorkflowInstancePayloadResponse
      rpc :ActivateJobs, ActivateJobsRequest, stream(ActivateJobsResponse)
      rpc :ListWorkflows, ListWorkflowsRequest, ListWorkflowsResponse
      rpc :GetWorkflow, GetWorkflowRequest, GetWorkflowResponse
      rpc :ResolveIncident, ResolveIncidentRequest, ResolveIncidentResponse
    end

    Stub = Service.rpc_stub_class
  end
end
